### ISSUE TITLE
invalid config-template/module_scoutnetauth.php

### ISSUE THREAD

**Issue by puggan** [Scouterna/simplesamlphp-module-scoutnetmodule#15]
config-template/module_scoutnetauth.php börjar med
`config = [`

vad är config, just nu är den en undefined constant, ska det vara en variable? typ `$config`,
används filen?

**Comment by Klako** [comment]
Tror inte att filen används.
Utifrån vad som står om simplesamlphps egna [config-template-mapp](https://simplesamlphp.org/docs/stable/simplesamlphp-install#section_3_1) så tror jag att det bara är en referens för när man skriver den riktiga konfigen, var den nu ligger.

SCOUTNET_HOSTNAME används direkt i [scoutnetauth.php](https://github.com/Scouterna/simplesamlphp-module-scoutnetmodule/blob/c2b33063af00b4ed58741afefe2cb97206deed55/lib/Auth/Source/scoutnetauth.php#L9)
