### ISSUE TITLE
missing return statement

### ISSUE THREAD

**Issue by puggan** [Scouterna/simplesamlphp-module-scoutnetmodule#4]
If niether of `$authResultObj->member->member_no` or `$authResultObj->err` is set,
the function neither return a value or throws an error (implicit void return).

Current:
https://github.com/Scouterna/simplesamlphp-module-scoutnetmodule/blob/22bb97dc27892f0c187b4e444a258082aee477a3/lib/Auth/Source/scoutnetauth.php#L103

After #3:
https://github.com/puggan/simplesamlphp-module-scoutnetmodule/blob/e73ea2bab58298285ec8e47017b9a32a8f860b00/lib/Auth/Source/scoutnetauth.php#L39

**Comment by Klako** [comment]
Förmodligen fixat...
