### ISSUE TITLE
above_15 always 0?

### ISSUE THREAD

**Issue by mrManner** [Scouterna/simplesamlphp-module-scoutnetmodule#7]
Needs further investigation, but it looks like we always get 0/false when calculating whether a user is above 15.

**Comment by puggan** [comment]
Always inverted?
![Screenshot from 2019-07-08 19-37-19](https://user-images.githubusercontent.com/866668/60830577-d409a600-a1b7-11e9-8843-73b526db03f7.png)

See PR #8

**Comment by mrManner** [comment]
Haha I should have seen that... Can't even blame my non-existing PHP skills.

Thanks =)
